
VERILOG_SOURCES=../../../config/optimsoc-config.sv noc_mux_wrapper.sv ../../verilog/noc_mux.sv ../../../wb_interconnect/verilog/wb_interconnect_arb_rr.v
TOPLEVEL=noc_mux_wrapper
MODULE=test_noc_mux
EXTRA_ARGS=-g2012

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim

