
VERILOG_SOURCES=noc_demux_wrapper.sv ../../verilog/noc_demux.sv
TOPLEVEL=noc_demux_wrapper
MODULE=test_noc_demux
EXTRA_ARGS=-g2012

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim

